config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  root "lists#index"

  resources :lists, only: [ :show, :create, :destroy ] do
    resources :bookmarks, only: [ :create ]
  end
  resources :bookmarks, only: [ :destroy ]



  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }

end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:create]

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @movies = @list.movies
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render "lists/show", status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @movies = @list.movies
    @bookmark = Bookmark.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :index, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<div class="container">
  <h1>Lists</h1>


<div class="row row-cols-3 g-3">
    <% @lists.each do |list| %>
      <div class="col">
          <div class="card h-100">
            <%= cl_image_tag list.photo.key, alt: list.name, class: "card-img-top fixed-img" %>
            <div class="card-body">
              <h5 class="card-title"><%= list.name.capitalize %></h5>
              <%= link_to "See list", list_path(list), class: "btn btn-secondary" %>
              <%= link_to "Delete list", list_path(list), 
                data: {turbo_method: :delete, turbo_confirm: "Are you sure?" },
                class: "btn btn-outline-secondary" %>
            </div>
          </div>   
      </div>
    <% end %>
</div>

<%# height: "200px"  w-100 %>
<br>
<br>
  <h2>Create new list</h2>

  <%= render "form", list: @list %>

</div>

app/views/lists/show.html.erb
<div class="container">
  <div class="row">
    <%= link_to "Go back to full list", root_path %>

    <h1><%= @list.name.capitalize %> with the following movies</h1>

    <div class="row row-cols-3 g-5">
      <% @movies.each do |movie| %>
        <div class="col">
          <div class="card h-100">
            <%= image_tag movie.poster_url, alt: movie.title, class: "card-img-top" %>
            <div class="card-body d-flex flex-column">
              <h5 class="card-title"><%= movie.title %></h5>
              <p class="card-text flex-grow-1"><%= movie.overview %></p>
              <%= link_to "Delete from list", bookmark_path(Bookmark.find_by(movie: movie, list: @list)), 
                data: {turbo_method: :delete, turbo_confirm: "Are you sure?" },
                class: "btn btn-outline-secondary mt-auto" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <h2>Add new movies to list</h2>

    <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.input :comment %>
      <%= f.association :movie %>
      <%= f.submit %>
    <% end %>
  </div>
</div>